let books = [
    {
        id: 1,
        img: "https://cdn1.fahasa.com/media/catalog/product/8/9/8935278605546.jpg",
        title: "30 Tuổi - Mọi Thứ Chỉ Mới Bắt Đầu",
        originalPrice: 125000, // Giá gốc (số)
        price: 100000,         // Giá sau giảm
        discountPercent: 20,   // % Giảm giá
        sku: "8935278605546",
        supplier: "Saigon Books",
        author: "Lý Thượng Long",
        publisher: "Dân Trí",
        publishYear: 2023,
        weight: "350g",
        size: "20.5 × 14 × 1.7 cm",
        pages: 332,
        format: "Bìa mềm",
        highlight: "Top 100 sách kỹ năng bán chạy tháng"
    },
    {
        id: 2,
        img: "https://cdn1.fahasa.com/media/catalog/product/c/h/chu-nghia-khac-ky-_tb-2023__bia-1.jpg",
        title: "Chủ Nghĩa Khắc Kỷ - Phong Cách Sống Bản Lĩnh Và Bình Thản (Tái Bản)",
        originalPrice: 130000,
        price: 104000,
        discountPercent: 20,
        sku: "8935235235231",
        supplier: "First News",
        author: "Marcus Aurelius",
        publisher: "NXB Tổng Hợp TP.HCM",
        publishYear: 2023,
        weight: "300g",
        size: "20.5 × 13 × 1.5 cm",
        pages: 280,
        format: "Bìa mềm",
        highlight: "Sách triết học bán chạy"
    },
    {
        id: 3,
        img: "https://cdn1.fahasa.com/media/catalog/product/9/7/9786044009674.jpg",
        title: "Con Đường Chẳng Mấy Ai Đi",
        originalPrice: 110000,
        price: 99000,
        discountPercent: 10,
        sku: "9786044009674",
        supplier: "Alpha Books",
        author: "M. Scott Peck",
        publisher: "NXB Thế Giới",
        publishYear: 2022,
        weight: "320g",
        size: "20 × 13 × 1.8 cm",
        pages: 360,
        format: "Bìa mềm",
        highlight: "Sách tâm lý học kinh điển"
    },
    {
        id: 4,
        img: "https://cdn1.fahasa.com/media/catalog/product/8/9/8936225390492.jpg",
        title: "Phương Pháp Đặt Câu Hỏi Của Socrates",
        originalPrice: 99000,
        price: 69300,
        discountPercent: 30,
        sku: "8936225390492",
        supplier: "Minh Long Books",
        author: "Ward Farnsworth",
        publisher: "NXB Hồng Đức",
        publishYear: 2021,
        weight: "280g",
        size: "20 × 13 × 1.4 cm",
        pages: 250,
        format: "Bìa mềm",
        highlight: "Rèn luyện tư duy phản biện"
    },
    {
        id: 5,
        img: "https://cdn1.fahasa.com/media/catalog/product/_/2/_2024_-thay_doi_ti_hon_hieu_qua_bat_ngo-tb8-02.jpg",
        title: "Atomic Habits - Thay Đổi Tí Hon Hiệu Quả Bất Ngờ",
        originalPrice: 165000,
        price: 132000,
        discountPercent: 20,
        sku: "8935251412345",
        supplier: "Alpha Books",
        author: "James Clear",
        publisher: "NXB Thế Giới",
        publishYear: 2023,
        weight: "350g",
        size: "20.5 × 13.5 × 1.7 cm",
        pages: 320,
        format: "Bìa mềm",
        highlight: "Top sách phát triển bản thân bán chạy"
    },
    {
        id: 6,
        img: "https://cdn1.fahasa.com/media/catalog/product/l/e/lennui-front_1.jpg",
        title: "Lên Đỉnh Núi Mở Tiệm Bánh Mì",
        originalPrice: 105000,
        price: 84000,
        discountPercent: 20,
        sku: "8935280909090",
        supplier: "Nhã Nam",
        author: "Naoki Matayoshi",
        publisher: "NXB Hội Nhà Văn",
        publishYear: 2022,
        weight: "270g",
        size: "19 × 13 × 1.5 cm",
        pages: 240,
        format: "Bìa mềm",
        highlight: "Sách truyền cảm hứng sống chậm"
    }
];